name: Build and Release

on:
  push:
    branches:
      - '*'

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js v18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install pnpm v8.x
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install deps
        run: pnpm i

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
